services:
  db:
    image: postgres:16.2-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

  redis:
    image: redis:7-alpine
    networks:
      - backend

  back:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - db
      - redis
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
